### ISSUE TITLE
[bug] Crash when using less-loader >= ^8.0.0

### ISSUE THREAD

**Issue by ShellWen** [xyy94813/customize-cra-less-loader#1]
It's work with less-loader 7.1.1 but not with 9.0.0

Error message:
```
TypeError: this.getOptions is not a function
```

This project is very helpful for me. Thanks for your contribution!

**Comment by ShellWen** [comment]
and it also not work on >= ^8.0.0

**Comment by ShellWen** [comment]
@xyy94813

**Comment by xyy94813** [comment]
Can you provide error messages？

Are you sure you're using webpack v5 and node version > 12.13.0?

https://github.com/webpack-contrib/less-loader/releases/tag/v9.0.0
https://github.com/webpack-contrib/less-loader/releases/tag/v8.0.0

**Comment by ShellWen** [comment]
诶，才发现是国人啊，用什么英语（
我现在电脑关机了，我明天去看看，用的是 create-react-app 默认的，貌似不是这个仓库的问题，我明天确认一下
